CREATE TABLE filters (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    field TEXT NOT NULL,
    operator TEXT NOT NULL DEFAULT "CONTAINS",
    value TEXT NOT NULL,
    logical_operator TEXT NOT NULL DEFAULT "AND",
    feed_id INTEGER NOT NULL REFERENCES feeds(id),
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
