/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoldersFolderNameRouteImport } from './routes/folders.$folderName'
import { Route as FeedsFeedIdRouteImport } from './routes/feeds.$feedId'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles.$articleId'
import { Route as AccountAccountIdRouteImport } from './routes/account.$accountId'

const TodayLazyRouteImport = createFileRoute('/today')()
const Read_laterLazyRouteImport = createFileRoute('/read_later')()
const OnboardingLazyRouteImport = createFileRoute('/onboarding')()
const New_feedLazyRouteImport = createFileRoute('/new_feed')()
const ConfigurationsLazyRouteImport = createFileRoute('/configurations')()
const AboutLazyRouteImport = createFileRoute('/about')()

const TodayLazyRoute = TodayLazyRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/today.lazy').then((d) => d.Route))
const Read_laterLazyRoute = Read_laterLazyRouteImport.update({
  id: '/read_later',
  path: '/read_later',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/read_later.lazy').then((d) => d.Route))
const OnboardingLazyRoute = OnboardingLazyRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/onboarding.lazy').then((d) => d.Route))
const New_feedLazyRoute = New_feedLazyRouteImport.update({
  id: '/new_feed',
  path: '/new_feed',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/new_feed.lazy').then((d) => d.Route))
const ConfigurationsLazyRoute = ConfigurationsLazyRouteImport.update({
  id: '/configurations',
  path: '/configurations',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/configurations.lazy').then((d) => d.Route),
)
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const FoldersFolderNameRoute = FoldersFolderNameRouteImport.update({
  id: '/folders/$folderName',
  path: '/folders/$folderName',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsFeedIdRoute = FeedsFeedIdRouteImport.update({
  id: '/feeds/$feedId',
  path: '/feeds/$feedId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountIdRoute = AccountAccountIdRouteImport.update({
  id: '/account/$accountId',
  path: '/account/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/configurations': typeof ConfigurationsLazyRoute
  '/new_feed': typeof New_feedLazyRoute
  '/onboarding': typeof OnboardingLazyRoute
  '/read_later': typeof Read_laterLazyRoute
  '/today': typeof TodayLazyRoute
  '/account/$accountId': typeof AccountAccountIdRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
  '/folders/$folderName': typeof FoldersFolderNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/configurations': typeof ConfigurationsLazyRoute
  '/new_feed': typeof New_feedLazyRoute
  '/onboarding': typeof OnboardingLazyRoute
  '/read_later': typeof Read_laterLazyRoute
  '/today': typeof TodayLazyRoute
  '/account/$accountId': typeof AccountAccountIdRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
  '/folders/$folderName': typeof FoldersFolderNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/configurations': typeof ConfigurationsLazyRoute
  '/new_feed': typeof New_feedLazyRoute
  '/onboarding': typeof OnboardingLazyRoute
  '/read_later': typeof Read_laterLazyRoute
  '/today': typeof TodayLazyRoute
  '/account/$accountId': typeof AccountAccountIdRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
  '/folders/$folderName': typeof FoldersFolderNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/configurations'
    | '/new_feed'
    | '/onboarding'
    | '/read_later'
    | '/today'
    | '/account/$accountId'
    | '/articles/$articleId'
    | '/feeds/$feedId'
    | '/folders/$folderName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/configurations'
    | '/new_feed'
    | '/onboarding'
    | '/read_later'
    | '/today'
    | '/account/$accountId'
    | '/articles/$articleId'
    | '/feeds/$feedId'
    | '/folders/$folderName'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/configurations'
    | '/new_feed'
    | '/onboarding'
    | '/read_later'
    | '/today'
    | '/account/$accountId'
    | '/articles/$articleId'
    | '/feeds/$feedId'
    | '/folders/$folderName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ConfigurationsLazyRoute: typeof ConfigurationsLazyRoute
  New_feedLazyRoute: typeof New_feedLazyRoute
  OnboardingLazyRoute: typeof OnboardingLazyRoute
  Read_laterLazyRoute: typeof Read_laterLazyRoute
  TodayLazyRoute: typeof TodayLazyRoute
  AccountAccountIdRoute: typeof AccountAccountIdRoute
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  FeedsFeedIdRoute: typeof FeedsFeedIdRoute
  FoldersFolderNameRoute: typeof FoldersFolderNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read_later': {
      id: '/read_later'
      path: '/read_later'
      fullPath: '/read_later'
      preLoaderRoute: typeof Read_laterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new_feed': {
      id: '/new_feed'
      path: '/new_feed'
      fullPath: '/new_feed'
      preLoaderRoute: typeof New_feedLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurations': {
      id: '/configurations'
      path: '/configurations'
      fullPath: '/configurations'
      preLoaderRoute: typeof ConfigurationsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folderName': {
      id: '/folders/$folderName'
      path: '/folders/$folderName'
      fullPath: '/folders/$folderName'
      preLoaderRoute: typeof FoldersFolderNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/$feedId': {
      id: '/feeds/$feedId'
      path: '/feeds/$feedId'
      fullPath: '/feeds/$feedId'
      preLoaderRoute: typeof FeedsFeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountId': {
      id: '/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/account/$accountId'
      preLoaderRoute: typeof AccountAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutLazyRoute: AboutLazyRoute,
  ConfigurationsLazyRoute: ConfigurationsLazyRoute,
  New_feedLazyRoute: New_feedLazyRoute,
  OnboardingLazyRoute: OnboardingLazyRoute,
  Read_laterLazyRoute: Read_laterLazyRoute,
  TodayLazyRoute: TodayLazyRoute,
  AccountAccountIdRoute: AccountAccountIdRoute,
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  FeedsFeedIdRoute: FeedsFeedIdRoute,
  FoldersFolderNameRoute: FoldersFolderNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
